import { test, expect } from '@playwright/test';

test('real invalid credentials, long inputs, special characters, and assistant recovery', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Email address').fill('patient@healthroute.local');
  await dialog.getByLabel('Password').fill('IncorrectPassword123!');
  await dialog.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Email or password is incorrect');
  await expect(page.getByRole('region', { name: 'Account access' })).toContainText('Guest access');
  await dialog.getByLabel('Password').fill('DemoPass123!');
  await dialog.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(dialog).toBeHidden();
  const search = page.getByLabel('What service are you looking for?');
  await search.fill('x'.repeat(250));
  await expect(search).toHaveValue('x'.repeat(200));
  await expect(page.getByText('No matching departments found')).toBeVisible();
  await search.fill("<script>alert('test')</script> & ' OR 1=1 --");
  await expect(page.getByText('No matching departments found')).toBeVisible();
  await page.getByRole('button', { name: 'Clear search', exact: true }).click();
  await expect(page.locator('.department-card').first()).toBeVisible();
  const question = page.getByLabel('Your navigation question');
  await question.fill(' ');
  await page.getByRole('button', { name: 'Find my route', exact: true }).click();
  await expect(page.locator('#question-error')).toBeVisible();
  await question.fill('z'.repeat(550));
  await expect(question).toHaveValue('z'.repeat(500));
  await page.getByRole('button', { name: 'Find my route', exact: true }).click();
  await expect(page.locator('.matching-intro')).toContainText('No matching service');
  await question.fill('Where can I get an X-ray?');
  await page.getByRole('button', { name: 'Find my route', exact: true }).click();
  await expect(page.locator('.recommendation-card').first().getByRole('heading', { level: 3 })).toHaveText('Radiology');
  await page.setViewportSize({ width: 320, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Account access' })).toContainText('Guest access');
  expect(errors).toEqual([]);
});
